services:
  app:
    image: ghcr.io/anne-munition/stream-info:latest
    container_name: stream-info
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ${LOG_PATH}:/app/logs:rw
    environment:
      NO_ACTIONS: ${NO_ACTIONS}
      LASTFM_API_KEY: ${LASTFM_API_KEY}
      MONGO_URL: ${MONGO_URL}
      TOKEN_AWS_URL: ${TOKEN_AWS_URL}
      TOKEN_AWS_API_KEY: ${TOKEN_AWS_API_KEY}
      SESSION_SECRET: ${SESSION_SECRET}
      TWITCH_CLIENT_ID: ${TWITCH_CLIENT_ID}
      TWITCH_CLIENT_SECRET: ${TWITCH_CLIENT_SECRET}
      TWITCH_CALLBACK_URL: ${TWITCH_CALLBACK_URL}
      TWITCH_EVENT_SUB_URL: ${TWITCH_EVENT_SUB_URL}
      ALLOWED_IDS: ${ALLOWED_IDS}
      STREAMELEMENTS_JWT: ${STREAMELEMENTS_JWT}
      STREAMELEMENTS_TOKEN: ${STREAMELEMENTS_TOKEN}
      DISCORD_SUS_FOLLOWER_URL: ${DISCORD_SUS_FOLLOWER_URL}
      DISCORD_REDDIT_URL: ${DISCORD_REDDIT_URL}
      PUSHOVER_USER: ${PUSHOVER_USER}
      PUSHOVER_TOKEN: ${PUSHOVER_TOKEN}
      STREAMDECK_TOKEN: ${STREAMDECK_TOKEN}
      REDDIT_CLIENT_ID: ${REDDIT_CLIENT_ID}
      REDDIT_CLIENT_SECRET: ${REDDIT_CLIENT_SECRET}
      REDDIT_USERNAME: ${REDDIT_USERNAME}
      REDDIT_PASSWORD: ${REDDIT_PASSWORD}
