name: Backend CI

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
    - uses: actions/checkout@v2
    - uses: c-hive/gha-yarn-cache@v2
      with:
        directory: ./backend
    - uses: actions/setup-node@v2
      with:
        node-version: 16
    - run: yarn install --immutable --immutable-cache --check-cache
    - run: yarn prettier
    - run: yarn lint
    - run: yarn test
