name: Test Build on Dev Branch

on:
  push:
    branches: [ dev ]

env:
  REGISTRY: "registry.digitalocean.com/dbkynd"
  IMAGE_NAME: "stream-info"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v1
      - uses: docker/build-push-action@v2
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
