name: Deploy to Digital Ocean

on:
  push:
    branches: [ dev ]

env:
  REGISTRY: "registry.digitalocean.com/dbkynd"
  IMAGE_NAME: "streaminfo"

jobs:
  build_backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./backend-Dockerfile
          tags: backend:latest
          outputs: type=docker,dest=/tmp/backend.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: backend
          path: /tmp/backend.tar

  build_frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./frontend-Dockerfile
          tags: frontend:latest
          outputs: type=docker,dest=/tmp/frontend.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: frontend
          path: /tmp/frontend.tar

  merge_images:
    runs-on: ubuntu-latest
    needs: [build_frontend, build_backend]
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Download backend artifact
        uses: actions/download-artifact@v2
        with:
          name: backend
          path: /tmp

      - name: Load Backend Docker image
        run: docker load --input /tmp/backend.tar

      - name: Download frontend artifact
        uses: actions/download-artifact@v2
        with:
          name: frontend
          path: /tmp

      - name: Load Frontend Docker image
        run: docker load --input /tmp/frontend.tar
        
